# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MemoryGame' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MemoryGame
  pod 'Nimble'
  pod 'Quick'

  target 'MemoryGameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MemoryGameUITests' do
    # Pods for testing
  end

end
